
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8768

spring:
  application:
    name: springcloud-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-hystrix
    api-b:
      path: /api-b/**
      serviceId: springcloud-hystrix-feign