
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

# 本地文件配置
#spring:
#  application:
#    name: springcloud-configserver
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config


# 远程github配置
spring:
  application:
    name: springcloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          username:
          password:
      label: master




